In [10]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

In [11]:
iris = load_iris()

In [12]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [13]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [14]:
print(iris.data[0])

[ 5.1  3.5  1.4  0.2]


In [15]:
print(iris.target[0])

0


In [16]:
for i in range(len(iris.target)):
    print("Example %d : Label %s, feature %s" % (i, iris.target[i], iris.data[i]))

Example 0 : Label 0, feature [ 5.1  3.5  1.4  0.2]
Example 1 : Label 0, feature [ 4.9  3.   1.4  0.2]
Example 2 : Label 0, feature [ 4.7  3.2  1.3  0.2]
Example 3 : Label 0, feature [ 4.6  3.1  1.5  0.2]
Example 4 : Label 0, feature [ 5.   3.6  1.4  0.2]
Example 5 : Label 0, feature [ 5.4  3.9  1.7  0.4]
Example 6 : Label 0, feature [ 4.6  3.4  1.4  0.3]
Example 7 : Label 0, feature [ 5.   3.4  1.5  0.2]
Example 8 : Label 0, feature [ 4.4  2.9  1.4  0.2]
Example 9 : Label 0, feature [ 4.9  3.1  1.5  0.1]
Example 10 : Label 0, feature [ 5.4  3.7  1.5  0.2]
Example 11 : Label 0, feature [ 4.8  3.4  1.6  0.2]
Example 12 : Label 0, feature [ 4.8  3.   1.4  0.1]
Example 13 : Label 0, feature [ 4.3  3.   1.1  0.1]
Example 14 : Label 0, feature [ 5.8  4.   1.2  0.2]
Example 15 : Label 0, feature [ 5.7  4.4  1.5  0.4]
Example 16 : Label 0, feature [ 5.4  3.9  1.3  0.4]
Example 17 : Label 0, feature [ 5.1  3.5  1.4  0.3]
Example 18 : Label 0, feature [ 5.7  3.8  1.7  0.3]
Example 19 : Label 0, 

In [17]:
test_idx = [0, 50, 100]

In [18]:
#Training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

In [19]:
#Testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

In [21]:
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [22]:
print(test_target)

[0 1 2]


In [23]:
print(clf.predict(test_data))

[0 1 2]


In [24]:
# Visualization code
from sklearn.externals.six import StringIO
import pydot
dot_data = StringIO()
tree.export_graphviz(clf, 
                     out_file = dot_data, 
                     feature_names = iris.feature_names, 
                     class_names = iris.target_names, 
                     filled = True, 
                     rounded = True, 
                     impurity = False)
graph = pydot.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("iris.pdf")

ModuleNotFoundError: No module named 'pydot'

In [27]:
print(test_data[1], test_target[1])

[ 7.   3.2  4.7  1.4] 1


In [28]:
print(iris.feature_names, print(iris.target_names))

['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] None
